# Generated by Django 3.2.9 on 2022-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220108_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='biology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='rollNo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
